### ISSUE TITLE
Bug in evaluateBoard() in tic-tac-toe example (docs)

### ISSUE THREAD

**Issue by zachtango** [turnbasedgames/urturn#110]
**Describe the bug**
The ordering of the condition checking in evaluateBoard is off. Right now, it checks for a tie first before a win. When a player wins, the function will output a tie rather than a win if the player won with all the squares in the board filled.

**To Reproduce**
1. https://docs.urturn.app/docs/Getting-Started/tictactoe
2. Scroll down to the evaluatedBoard function Solution tab.

**Comment by kevo1ution** [comment]
Good find!
