### ISSUE TITLE
Bug in logic of onPlayerQuit function of tic tac toe example: loser becomes winner

### ISSUE THREAD

**Issue by zachtango** [turnbasedgames/urturn#119]
**Describe the bug**
The bug is in the tic tac toe example on the docs. In the onPlayerQuit function, the winner is set to the person in the room after the other player leaves. Consider the case of player L (loser) and player W (winner). Player W leaves the game first, resulting in player L being changed to the winner.

**To Reproduce**
1. Go to https://docs.urturn.app/docs/Getting-Started/tictactoe#players-leaving
2. Click onPlayerQuit solution
3. The bug is also in the examples/tic-tac-toe folder of the repo

**Comment by kevo1ution** [comment]
onPlayerQuit cannot be called if the room is set to `finished`: https://docs.urturn.app/docs/API/types#roomstate
So if player W exists then that implies `finished: true`
