### ISSUE TITLE
Add phaser.io template

### ISSUE THREAD

**Issue by Enjoy2Live** [turnbasedgames/urturn#142]
**Is your feature request related to a problem? Please describe.**
So far the templates we have are just vanilla js and react and those don't provide functions and utilities for creating web based games, you'd have build them manually yourself from the scratch.

**Describe the solution you'd like**
[Phaser.io](https://phaser.io/) is a canvas/webgl game framework that has a ton of functions and utilities to make creating games on the web an easier task compared to writing those in vanilla js or react.
By creating a template that uses phaser.io users can get started quickly building their multiplayer games in ease!

**Comment by Enjoy2Live** [comment]
I'm interested in implementing this so could you please assign me to this issue? @kevo1ution

**Comment by kevo1ution** [comment]
Hey @Enjoy2Live, this is a great idea. Hopefully, you can help us out with your knowledge of `phaser.io`. I will be adding a README.md shortly to the `/templates` folder to outline instructions on local development environment to help make your work easier. I'll link the PR to this GH issue. Looking forward to seeing what you come up with :)

**Comment by kevo1ution** [comment]
Thanks for adding this! It's been released to prod!
